version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  elasticsearch:
    image: 'elasticsearch:5'
    ports:
      - '9200:9200'
    volumes:
      - 'elastic:/usr/share/elasticsearch/data'
    environment:
      - Des.network.host=0.0.0.0

  api:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/fractal'
      - gems:/gems
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  postgres:
  box:
  gems:
  elastic: